export default {
  TOGGLE_SIDE_MENU: 'TOGGLE_SIDE_MENU',

  GET_ALL_TITLES: 'GET_ALL_TITLES',
  GET_ALL_TITLES_REQUEST: 'GET_ALL_TITLES_REQUEST',
  GET_ALL_TITLES_SUCCESS: 'GET_ALL_TITLES_SUCCESS',
  GET_ALL_TITLES_FAILURE: 'GET_ALL_TITLES_FAILURE',
};
