export default {
  TOGGLE_SIDE_MENU: 'TOGGLE_SIDE_MENU',

  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',

  CURRENT_PAGE_INCREMENT: 'CURRENT_PAGE_INCREMENT',
  CURRENT_PAGE_DECREMENT: 'CURRENT_PAGE_DECREMENT',
  CURRENT_PAGE_RESET: 'CURRENT_PAGE_RESET',

  GET_ALL_TITLES: 'GET_ALL_TITLES',
  GET_ALL_TITLES_REQUEST: 'GET_ALL_TITLES_REQUEST',
  GET_ALL_TITLES_SUCCESS: 'GET_ALL_TITLES_SUCCESS',
  GET_ALL_TITLES_FAILURE: 'GET_ALL_TITLES_FAILURE',
};
