export default {
  TOGGLE_SIDE_MENU: 'TOGGLE_SIDE_MENU',

  TOGGLE_MODAL: 'TOGGLE_MODAL',

  UPGRADE_WATCH_LIST: 'UPGRADE_WATCH_LIST',
  UPGRADE_VIEWED_LIST: 'UPGRADE_VIEWED_LIST',
  UPGRADE_FAVORITE_LIST: 'UPGRADE_FAVORITE_LIST',
  UPGRADE_BLACK_LIST: 'UPGRADE_BLACK_LIST',

  GET_FIRST_DATA: 'GET_FIRST_DATA',

  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',

  CURRENT_PAGE_INCREMENT: 'CURRENT_PAGE_INCREMENT',
  CURRENT_PAGE_DECREMENT: 'CURRENT_PAGE_DECREMENT',
  CURRENT_PAGE_RESET: 'CURRENT_PAGE_RESET',

  GET_ALL_TITLES: 'GET_ALL_TITLES',
  GET_ALL_TITLES_REQUEST: 'GET_ALL_TITLES_REQUEST',
  GET_ALL_TITLES_SUCCESS: 'GET_ALL_TITLES_SUCCESS',
  GET_ALL_TITLES_FAILURE: 'GET_ALL_TITLES_FAILURE',

  GET_TITLE_BY_ID: 'GET_TITLE_BY_ID',
  GET_TITLE_BY_ID_REQUEST: 'GET_TITLE_BY_ID_REQUEST',
  GET_TITLE_BY_ID_SUCCESS: 'GET_TITLE_BY_ID_SUCCESS',
  GET_TITLE_BY_ID_FAILURE: 'GET_TITLE_BY_ID_FAILURE',
};
